FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

COPY napcat_ai_bridge.py ./

EXPOSE 4000
CMD ["python","-u", "napcat_ai_bridge.py"]
